### ISSUE TITLE
[BUG] Something has been corrupted by the templater upgrade

### ISSUE THREAD

**Issue by Borber** [chhoumann/quickadd#109]
VM211:15097 QuickAdd: (LOG) TypeError: templater.templater.overwrite_file_templates is not a function

**Comment by chhoumann** [comment]
Hey, this should be fixed with 0.4.7. Can you confirm? :)

**Comment by Borber** [comment]
A new error has been reported

VM211:15096 QuickAdd: (LOG) TypeError: Cannot read property 'slice' of undefined

**Comment by Borber** [comment]
When capture creates a new file, the capture format will be invalid, a null value will be inserted, and the link will not be inserted into the current article. But if it is inserted directly into the capture of the current article, there is no problem

**Comment by Borber** [comment]
"TypeError: Cannot read property 'slice' of undefined
    at parse (eval at <anonymous> (app://obsidian.md/app.js:1:1257795), <anonymous>:5042:20)
    at compileToString (eval at <anonymous> (app://obsidian.md/app.js:1:1257795), <anonymous>:5066:18)
    at compile (eval at <anonymous> (app://obsidian.md/app.js:1:1257795), <anonymous>:5286:9)
    at handleCache (eval at <anonymous> (app://obsidian.md/app.js:1:1257795), <anonymous>:5533:68)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1257795), <anonymous>:5579:33)
    at new Promise (<anonymous>)
    at render (eval at <anonymous> (app://obsidian.md/app.js:1:1257795), <anonymous>:5577:24)
    at renderAsync (eval at <anonymous> (app://obsidian.md/app.js:1:1257795), <anonymous>:5611:12)
    at Parser.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1257795), <anonymous>:5622:30)
    at Generator.next (<anonymous>)"

**Comment by chhoumann** [comment]
Thank you! I'll look into it.

**Comment by chhoumann** [comment]
Hey! I've found what seems to be a fix (after lots of testing). Can you confirm? :)

**Comment by Borber** [comment]
> Hey! I've found what seems to be a fix (after lots of testing). Can you confirm? :)

It works perfectly, thank you very much!
