### ISSUE TITLE
[BUG] Movie script is not working

### ISSUE THREAD

**Issue by kmaustral** [chhoumann/quickadd#629]
This script has been of enduring use. 

**Describe the bug**
The movie script previously worked fine, but now it generates this error in the console:

TypeError: Failed to construct 'URL': Invalid URL
    at qw (app.js:1:748288)
    at enter (app.js:1:1553533)
    at e.iterate (app.js:1:548850)
    at Uu.iterate (app.js:1:2018538)
    at u (app.js:1:1552229)
    at e.update [as updateF] (app.js:1:1555718)
    at Object.update (app.js:1:295711)
    at e.computeSlot (app.js:1:306504)
    at fi (app.js:1:299655)
    at new e (app.js:1:305530)
    at e.applyTransaction (app.js:1:306446)
    at e.get (app.js:1:301659)
    at Array.eval (plugin:make-md:54225:14)
    at app.js:1:304425
    at Pi (app.js:1:304523)
    at e.update (app.js:1:305856)
    at ms (app.js:1:404668)
    at app.js:1:404812

I've tried this with a number of searches. 

I notice also that the URL previously put the IMDB code in quotation marks, which had to be deleted to open the link.

**Comment by chhoumann** [comment]
I investigated the example Movie user script and reproduced the  coming from the use of  in the script's  function.

I pushed a fix to the example script:
- Avoid using  (construct query string with  instead)
- Validate and require the OMDb API key in script settings
- Harden date parsing for unexpected  values (e.g., )
- Make list linkification and filename sanitization more robust

No changes to the plugin code were necessary; this was isolated to the docs/example script. Build and tests pass locally.

Updated file: 

Please try the updated script and let me know if the error persists or if you still see quotes around the IMDb ID in the resulting link. The script now produces  without quotes.
